### ISSUE TITLE
User roles and sharing

### ISSUE THREAD

**Issue by olavpo** [dhis2/dhis2-trainingland#10]
From Terje, Arthur, Matthieu

Some guidelines on managing user roles and sharing required

**Comment by olavpo** [comment]
Have you had a look at this?
https://github.com/dhis2/dhis2-trainingland/wiki/Trainingland-user-groups-sharing

**Comment by terjeasa** [comment]
I have not, but I will now. Thanks.

**Comment by olavpo** [comment]
Additional issue: new level of hierarchy for admins
