### ISSUE TITLE
1000 MVD indicators

### ISSUE THREAD

**Issue by olavpo** [dhis2/dhis2-trainingland#13]
From Terje, Arthur, Matthieu

Need data and indicators for 1000 most critical days Dashboard and exercises, a mock-up of such a Dashboard would be a good starting point

**Comment by olatitle** [comment]
What data and indicators are missing for the 1000 MVD use case(s)?

**Comment by terjeasa** [comment]
I think we need to do a Skype call on this and agree on a few indicators that we want to use as examples for DHIS2 Academies. I think we should also set up a 1000 MVD dashboard based on these indicators and write up some stories etc. It is not so much that data is missing  - I think we can make something from what we have. We just need to agree on what will serve as good examples and where we want to focus energy in terms of improving the data base. I guess it is not so much a Trainingland data issue, but a Trainingland teaching environment strategy issue.

**Comment by olavpo** [comment]
Needs to be revisited, much has happened since this was reported.
