### ISSUE TITLE
Need nutrition data 

### ISSUE THREAD

**Issue by terjeasa** [dhis2/dhis2-trainingland#30]
Needed for indicators stunting and wasting at age 5

**Comment by olavpo** [comment]
There are not (at least "officially") HMIS indicators, but should come come from surveys or surveillance systems. http://www.who.int/healthinfo/indicators/2015/chi_2015_55_children_stunted.pdf

**Comment by terjeasa** [comment]
Right, but we still want them in our integrated data repository?
