### ISSUE TITLE
Many indicators on core dashboards with data elements that are not shared properly

### ISSUE THREAD

**Issue by olatitle** [dhis2/dhis2-trainingland#31]
When opening the dashboards with a user with Data Analysis role + member of group "see predefined dashboards" I get a lot of empty charts and access errors in the js console.

Especially with HIV and Malaria dashboards, but a few in most of the dashboards.

Sees there are quite a few indicators that have been updated to use new data elements that are only shared with "Data Access - WHO" and not "Data Access - Core".

**Comment by olavpo** [comment]
Yes, a round of cleanup is needed here... In terms of dashboards and outputs, is what is there currently what will be used for the first "release"/trainings, or are more still being added?

A simple fix would be to add "Data Access - Core" to all data elements and indicators, unless there is WHO metadata that should be hidden for non-WHO users?
