### ISSUE TITLE
Enable encryption in Trainingland

### ISSUE THREAD

**Issue by shurajitdutta** [dhis2/dhis2-trainingland#33]
Would be nice to enable encryption in Trainingland for tracker.

**Comment by olatitle** [comment]
Yes, I guess it would be good to show that for one program as see how it
works.

The way encryption on patient attributes is done means that all searching
for these attributes is impossible so it has a lot of implications on
usability, e.g. if the identifier is lost you cannot use name, address etc.
to search and locate the patient. So in practice is requires a national ID
schema in place where patients do remember their ID.

But good to show two different approaches to patient security, one with
encryption and another with a more soft "break the glass" approach where
access is allowed, but logged and users forced to make comments/explain
they open files that are not by default "theirs". We're not there yet in
terms of all functionality, but would be good to start explaining these
concepts and approaches and how DHIS 2 can support these (partially or
fully).

Markus and Mike working on the Palestine project have a lot to share here I
think (on the softer "break the glass" approach").

---

Ola Hodne Titlestad (Mr)
HISP
Department of Informatics
University of Oslo

Mobile: +47 48069736
Home address: Eftasåsen 68, 0687 Oslo, Norway. Googlemaps link
https://maps.google.com/maps?q=Eftas%C3%A5sen+68,+0687+Oslo,+Norge&hl=en&ie=UTF8&sll=59.893855,10.785116&sspn=0.222842,0.585709&oq=eftas%C3%A5sen+68,+0687+Oslo,+&t=h&hnear=Eftas%C3%A5sen+68,+%C3%98stensj%C3%B8,+0687+Oslo,+Norway&z=16

**Comment by olavpo** [comment]
Moved to Jira
