### ISSUE TITLE
CoD favourites for public user not working correctly

### ISSUE THREAD

**Issue by shurajitdutta** [dhis2/dhis2-trainingland#37]
When trying to create a user that doesn't belong to any user group with basic data entry and analysis privileges the CoD dashboard and favourites that are publically available are not working.

**Comment by olavpo** [comment]
There shouldn't be any users without a user group - no data elements or indicators (or anything else ideally) are public, so they will not be able to see or do anything. I.e. if they see the CoD dashboard and favourites those need to be made non-public.
