### ISSUE TITLE
Skilled birth attendance

### ISSUE THREAD

**Issue by olavpo** [dhis2/dhis2-trainingland#6]
From Terje

Skilled birth attendance (%) for Trainingland is generally lower than institutional delivery rate (%). Is this intentional? Shouldn't most institutional deliveries be by skilled birth attendant, so that the latter indicator will always be higher than institutional delivery rate? Vegetable district is the exeption at least for some periods where institutional delivery is lower than skilled birth attendance.

**Comment by olavpo** [comment]
Not 100% if it is intended here, but I don't think this is uncommon in real life, since you might have facilities without skilled personnel doing deliveries.

Of course lots of questions on how you define "skilled", and also whether people will necessarily report correctly.

**Comment by olatitle** [comment]
Skilled should be same or lower than institutional deliveries. We need to check that it's not higher.

**Comment by olavpo** [comment]
Jira
