### ISSUE TITLE
Pussy dispensary

### ISSUE THREAD

**Issue by olavpo** [dhis2/dhis2-trainingland#9]
From Johan

pussy dispensary.. can we find a less gigglish name?

Spider is not an insect and whale is not a fish!!

**Comment by olavpo** [comment]
Anonymous: 
maybe leave spider and whale as an "easter egg" for inquisitive participants...

**Comment by russnes** [comment]
+1 for laughs

**Comment by olavpo** [comment]
Moved to jira
